### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by KyryloKilin** [FhenixProtocol/fhenix-docs#6]
A broken link on the page: https://fhenixprotocol.github.io/fhenix-docs/docs/devdocs/Examples%20and%20References/Examples-fheDapps/ 

![image](https://github.com/FhenixProtocol/fhenix-docs/assets/83702309/583ac5ce-4927-4f54-8d3a-f06ef759d4d3)

**Comment by Cashmaney** [comment]
Thanks. We still haven't fully updated that section
